/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lossless;

import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class Trans_Scall_rotat_for_2D extends javax.swing.JFrame {

    /**
     * Creates new form Trans_Scall_rotat_for_2D
     */
    public Trans_Scall_rotat_for_2D() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txt_num_point = new javax.swing.JTextField();
        rbtn_translation = new javax.swing.JRadioButton();
        rbtn_scaling = new javax.swing.JRadioButton();
        rbtn_rotation = new javax.swing.JRadioButton();
        btn_calculate = new javax.swing.JButton();
        btn_insert_points = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbl_result = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter num point : ");

        btn_group.add(rbtn_translation);
        rbtn_translation.setText("Translation");
        rbtn_translation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_translationActionPerformed(evt);
            }
        });

        btn_group.add(rbtn_scaling);
        rbtn_scaling.setText("Scaling");

        btn_group.add(rbtn_rotation);
        rbtn_rotation.setText("Rotation");

        btn_calculate.setText("Calculate");
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });

        btn_insert_points.setText("Insert points");
        btn_insert_points.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insert_pointsActionPerformed(evt);
            }
        });

        lbl_result.setEditable(false);
        lbl_result.setColumns(20);
        lbl_result.setLineWrap(true);
        lbl_result.setRows(5);
        jScrollPane1.setViewportView(lbl_result);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(rbtn_translation)
                        .addGap(18, 18, 18)
                        .addComponent(rbtn_scaling)
                        .addGap(37, 37, 37)
                        .addComponent(rbtn_rotation))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btn_calculate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_num_point, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btn_insert_points)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_num_point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_insert_points))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_translation)
                    .addComponent(rbtn_scaling)
                    .addComponent(rbtn_rotation))
                .addGap(18, 18, 18)
                .addComponent(btn_calculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn_translationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_translationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_translationActionPerformed

    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed
        if(this.rbtn_translation.isSelected())
           this.Translation();
        else if(this.rbtn_scaling.isSelected())
            this.Scaling();
        else if(this.rbtn_rotation.isSelected())
            this.Rotation();
        else
            JOptionPane.showMessageDialog(null, "not selected any of (translation, Rotation, Scaling)", "Alert", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_calculateActionPerformed

    private void btn_insert_pointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insert_pointsActionPerformed
        this.getpoints();
    }//GEN-LAST:event_btn_insert_pointsActionPerformed

    public void Rotation(){
        float Rotation_rate = Float.parseFloat(JOptionPane.showInputDialog(null, "Enter Angele of Rotation like", "input", JOptionPane.INFORMATION_MESSAGE));
        for (int i = 0; i < this.points.length; i++) {
            points[i][0]=(int) ((int) (points[i][0] * Math.floor(Math.cos(Math.toRadians(Rotation_rate)))) - (points[i][1] * Math.ceil(Math.sin(Math.toRadians(Rotation_rate)))));
            points[i][1]=(int) ((int) (points[i][0] * Math.ceil(Math.sin(Math.toRadians(Rotation_rate)))) + (points[i][1]*Math.floor(Math.cos(Math.toRadians(Rotation_rate)))));
        }
        String s = "Points : \n";
        for (int i = 0; i < this.points.length; i++) {
            s += "point(" + (i+1) + ") : (" + this.points[i][0] + ", " + this.points[i][1] + ")  \n";
        }
        
        this.lbl_result.setText(s);
    }
    
    public void Scaling(){
        String scall_rate = JOptionPane.showInputDialog(null, "Enter rate of Scaling like x,y", "input", JOptionPane.INFORMATION_MESSAGE);       
        String[] t = scall_rate.split(",");
        int sx = Integer.parseInt(t[0]);
        int sy = Integer.parseInt(t[1]);
        
        for (int i = 0; i < this.points.length; i++) {
            points[i][0]=points[i][0] * sx;
            points[i][1]=points[i][1] * sy;
        }
        
        scall_rate = "Points : \n";
        for (int i = 0; i < this.points.length; i++) {
            scall_rate += "point(" + (i+1) + ") : (" + this.points[i][0] + ", " + this.points[i][1] + ")  \n";
        }
        
        this.lbl_result.setText(scall_rate);
    }
    
    public void Translation(){
        
        String transl_rate = JOptionPane.showInputDialog(null, "Enter rate of trasnlation like x,y", "input", JOptionPane.INFORMATION_MESSAGE);       
        String[] t = transl_rate.split(",");
        int x = Integer.parseInt(t[0]);
        int y = Integer.parseInt(t[1]);
        
        for (int i = 0; i < this.points.length; i++) {
            points[i][0]=points[i][0] + x;
            points[i][1]=points[i][1] + y;
        }
        
        transl_rate = "Points : \n";
        for (int i = 0; i < this.points.length; i++) {
            transl_rate += "point(" + (i+1) + ") : (" + this.points[i][0] + ", " + this.points[i][1] + ")  \n";
        }
        
        this.lbl_result.setText(transl_rate);
        
    }
    
    public void getpoints(){
        
        if(this.txt_num_point.getText().equals(""))
            JOptionPane.showMessageDialog(null, "points cannet be empty", "Alert", JOptionPane.INFORMATION_MESSAGE);
        else{
            int n = Integer.parseInt(this.txt_num_point.getText());
            this.points = new int[n][n];
            String temp;
            for (int i = 0; i < n; i++) {
                temp = JOptionPane.showInputDialog(null, "point("+ (i+1) +") like x,y", "input", JOptionPane.INFORMATION_MESSAGE);
                String []t = temp.split(",");
                for (int j = 0; j < 2; j++) {
                    this.points[i][j] = Integer.parseInt(t[j]);
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trans_Scall_rotat_for_2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trans_Scall_rotat_for_2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trans_Scall_rotat_for_2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trans_Scall_rotat_for_2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trans_Scall_rotat_for_2D().setVisible(true);
            }
        });
    }

    public int[][]points;
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calculate;
    private javax.swing.ButtonGroup btn_group;
    private javax.swing.JButton btn_insert_points;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lbl_result;
    private javax.swing.JRadioButton rbtn_rotation;
    private javax.swing.JRadioButton rbtn_scaling;
    private javax.swing.JRadioButton rbtn_translation;
    private javax.swing.JTextField txt_num_point;
    // End of variables declaration//GEN-END:variables
}
